#!/bin/bash

if [ -z "$GIT_EMAIL" ]; then
 echo "You need to pass the \$GIT_EMAIL variable to the container for this to work"
 exit
fi

if [ -z "$GIT_NAME" ]; then
 echo "You need to pass the \$GIT_NAME variable to the container for this to work"
 exit
fi

cd /home/app/project
supervisorctl stop nodeserver
git pull
chown -Rf nginx:nginx /home/app/project
supervisorctl start nodeserver
